//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSummit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendee
    {
        public Nullable<int> Id { get; set; }
        public string Bio { get; set; }
        public string Name { get; set; }
        public string Company { get; set; }
        public string AvatarUrl { get; set; }
        public string MediumImage { get; set; }
        public string Career { get; set; }
        public int AutoId { get; set; }
        public string country { get; set; }
    }
}
