//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webSummit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Startup
    {
        public Nullable<int> Id { get; set; }
        public string Description { get; set; }
        public string brandisty_url { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Company { get; set; }
        public string Pitch { get; set; }
        public string MediumImage { get; set; }
        public string Industry { get; set; }
        public int AutoId { get; set; }
        public string country { get; set; }
        public string Track { get; set; }
        public string WebSite { get; set; }
        public string PastConference { get; set; }
    }
}
